# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44045a541735c9d41afc5d9bd9db8335b3de487c91807ae1c3e25ac248da95204e3b0d837751dda5241107aa234d2ba569abd546bbe3eee7ca406c82d31f29e9

test:
  secret_key_base: 5b671a2d29d231d368ec9f4552f0e89e3fc0e7732e808ed937ffb72273e505bed1ee3bfba5e4c0a8ffcdc223db64c980df3d38b16029cda4ef9b5c950342c3cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
